# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guests.Function'),
            preserve_default=False,
        ),
    ]
